locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
title_separator: "-"
name: &name "Junteng Liu"
description: &description "Junteng Liu's academic homepage"
url: "https://jun-7z.github.io"
baseurl: "/LJT-Homepage"
repository: "Jun-7z/LJT-Homepage"

# Site Author
author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  employer: "Hong Kong University of Science and Technology"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: false
read_more: "disabled"
talkmap_link: false
comments:
  provider: false
atom_feed:
  hide: true

# SEO / social
social:
  type: Person
  name: "Junteng Liu"
  links:
    - "https://github.com/Vicent0205"
    - "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
twitter:
  username: "junteng88716710"

# Analytics
analytics:
  provider: false

# Reading Files
include: []
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - _drafts
  - _pages
  - _portfolio
  - _posts
  - _publications
  - _talks
  - _teaching
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - docker-compose.yaml
  - files
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - markdown_generator
  - node_modules
  - package.json*
  - Rakefile
  - README
  - README.md
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - talkmap_out.ipynb
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
